export const typesList = {
  FETCH_ITEMS: 'FETCH_ITEMS',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
  RESET: 'RESET'
};

export const typesFaves = {
  PUSH_ITEM: 'PUSH_ITEM',
  DELETE_ITEM: 'DELETE_ITEM'
};

export const typesPage = {
  SET_TOTAL: 'SET_TOTAL',
  RESET_PAGE: 'RESET_PAGE',
  GO_NEXT: 'GO_NEXT',
  GO_PREV: 'GO_PREV',
  GO_SPECIAL: 'GO_SPECIAL'
};
